# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Mesh_config = debug
endif
ifeq ($(config),release)
  Mesh_config = release
endif

PROJECTS := Mesh

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Mesh:
ifneq (,$(Mesh_config))
	@echo "==== Building Mesh ($(Mesh_config)) ===="
	@${MAKE} --no-print-directory -C . -f Mesh.make config=$(Mesh_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Mesh.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Mesh"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"